//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dietphone.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dietphone.Views.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about app.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD CATEGORY.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NAME.
        /// </summary>
        public static string AddName {
            get {
                return ResourceManager.GetString("AddName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows sending data attached to an e-mail. The data will be in XML format..
        /// </summary>
        public static string AllowsSendingDataAttachedToAnEMail {
            get {
                return ResourceManager.GetString("AllowsSendingDataAttachedToAnEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to retrieve data from a file in XML format. The file that you previously sent to any server, e.g. Google Docs..
        /// </summary>
        public static string AllowsToRetrieveDataFromAFileInXmlFormat {
            get {
                return ResourceManager.GetString("AllowsToRetrieveDataFromAFileInXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during import. Make sure that the imported data were not corrupted..
        /// </summary>
        public static string AnErrorOccurredDuringImport {
            get {
                return ResourceManager.GetString("AnErrorOccurredDuringImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the imported data. Make sure that you have Internet access and address is correct..
        /// </summary>
        public static string AnErrorOccurredWhileRetrievingTheImportedData {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileRetrievingTheImportedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the exported data. Make sure that you have Internet access and e-mail address is valid..
        /// </summary>
        public static string AnErrorOccurredWhileSendingTheExportedData {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileSendingTheExportedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App language.
        /// </summary>
        public static string AppLanguage {
            get {
                return ResourceManager.GetString("AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete this category?
        ///
        ///{0}.
        /// </summary>
        public static string AreYouSureYouWantToPermanentlyDeleteThisCategory {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToPermanentlyDeleteThisCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete this meal?
        ///
        ///{0}.
        /// </summary>
        public static string AreYouSureYouWantToPermanentlyDeleteThisMeal {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToPermanentlyDeleteThisMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete this name?
        ///
        ///{0}.
        /// </summary>
        public static string AreYouSureYouWantToPermanentlyDeleteThisName {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToPermanentlyDeleteThisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete this product?
        ///
        ///{0}.
        /// </summary>
        public static string AreYouSureYouWantToPermanentlyDeleteThisProduct {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToPermanentlyDeleteThisProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save this meal?.
        /// </summary>
        public static string AreYouSureYouWantToSaveThisMeal {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToSaveThisMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save this product?.
        /// </summary>
        public static string AreYouSureYouWantToSaveThisProduct {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToSaveThisProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug!.
        /// </summary>
        public static string Bug {
            get {
                return ResourceManager.GetString("Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug in app! Report to the author?.
        /// </summary>
        public static string BugInAppReportToTheAuthor {
            get {
                return ResourceManager.GetString("BugInAppReportToTheAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cal.
        /// </summary>
        public static string Cal {
            get {
                return ResourceManager.GetString("Cal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete.
        /// </summary>
        public static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this name..
        /// </summary>
        public static string CannotDeleteThisName {
            get {
                return ResourceManager.GetString("CannotDeleteThisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit this name..
        /// </summary>
        public static string CannotEditThisName {
            get {
                return ResourceManager.GetString("CannotEditThisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t use serving size as a unit of size of serving size..
        /// </summary>
        public static string CantUseServingSizeAsAUnitOfSizeOfServingSize {
            get {
                return ResourceManager.GetString("CantUseServingSizeAsAUnitOfSizeOfServingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} carb.
        /// </summary>
        public static string Carb {
            get {
                return ResourceManager.GetString("Carb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbohydrates (g).
        /// </summary>
        public static string CarbohydratesG {
            get {
                return ResourceManager.GetString("CarbohydratesG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORY.
        /// </summary>
        public static string CategoryUppercase {
            get {
                return ResourceManager.GetString("CategoryUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes of language and localization will be applied the next time you start app..
        /// </summary>
        public static string ChangesOfLanguageAndLocalizationWillBeAppliedThe {
            get {
                return ResourceManager.GetString("ChangesOfLanguageAndLocalizationWillBeAppliedThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} CU.
        /// </summary>
        public static string Cu {
            get {
                return ResourceManager.GetString("Cu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CU - carbohydrate unit.
        /// </summary>
        public static string CuCarbohydrateUnit {
            get {
                return ResourceManager.GetString("CuCarbohydrateUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CU (Carbohydrate Unit) is quantity of carbohydrates in grams divided by 10. 
        ///Purpose is to facilitate the counting of carbohydrates in meals. Also known as Bread Unit..
        /// </summary>
        public static string CuIs {
            get {
                return ResourceManager.GetString("CuIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete category?.
        /// </summary>
        public static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete meal?.
        /// </summary>
        public static string DeleteMeal {
            get {
                return ResourceManager.GetString("DeleteMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete name?.
        /// </summary>
        public static string DeleteName {
            get {
                return ResourceManager.GetString("DeleteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product?.
        /// </summary>
        public static string DeleteProduct {
            get {
                return ResourceManager.GetString("DeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dietary fiber (g).
        /// </summary>
        public static string DietaryFiberG {
            get {
                return ResourceManager.GetString("DietaryFiberG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIETPHONE.
        /// </summary>
        public static string Dietphone {
            get {
                return ResourceManager.GetString("Dietphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digestible carbohydrates (grams).
        /// </summary>
        public static string DigestibleCarbohydratesGrams {
            get {
                return ResourceManager.GetString("DigestibleCarbohydratesGrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digestible carbs (g).
        /// </summary>
        public static string DigestibleCarbsG {
            get {
                return ResourceManager.GetString("DigestibleCarbsG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file from address.
        /// </summary>
        public static string DownloadFileFromAddress {
            get {
                return ResourceManager.GetString("DownloadFileFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT CATEGORY.
        /// </summary>
        public static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT NAME.
        /// </summary>
        public static string EditName {
            get {
                return ResourceManager.GetString("EditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to energy (calories).
        /// </summary>
        public static string EnergyCalories {
            get {
                return ResourceManager.GetString("EnergyCalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy (calories).
        /// </summary>
        public static string EnergyCaloriesUppercase {
            get {
                return ResourceManager.GetString("EnergyCaloriesUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export&amp;import.
        /// </summary>
        public static string ExportAndImport {
            get {
                return ResourceManager.GetString("ExportAndImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export and import data.
        /// </summary>
        public static string ExportAndImportData {
            get {
                return ResourceManager.GetString("ExportAndImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export completed successfully..
        /// </summary>
        public static string ExportCompletedSuccessfully {
            get {
                return ResourceManager.GetString("ExportCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} fat.
        /// </summary>
        public static string Fat {
            get {
                return ResourceManager.GetString("Fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat (g).
        /// </summary>
        public static string FatG {
            get {
                return ResourceManager.GetString("FatG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fat (grams).
        /// </summary>
        public static string FatGrams {
            get {
                return ResourceManager.GetString("FatGrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} FPU.
        /// </summary>
        public static string Fpu {
            get {
                return ResourceManager.GetString("Fpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPU - fat-protein unit.
        /// </summary>
        public static string FpuFatProteinUnit {
            get {
                return ResourceManager.GetString("FpuFatProteinUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPU (Fat-Protein Unit) means calories value coming from fat and protein divided by 100.
        ///So one number gives information on both fat and protein in meal..
        /// </summary>
        public static string FpuIs {
            get {
                return ResourceManager.GetString("FpuIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from Pabloware.
        /// </summary>
        public static string FromPabloware {
            get {
                return ResourceManager.GetString("FromPabloware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full square means maximum in category..
        /// </summary>
        public static string FullSquareMeansMaximumInCategory {
            get {
                return ResourceManager.GetString("FullSquareMeansMaximumInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import completed successfully..
        /// </summary>
        public static string ImportCompletedSuccessfully {
            get {
                return ResourceManager.GetString("ImportCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In 100 g of product, probably should be {0} calories (+/-{1} calories) but is {2} calories..
        /// </summary>
        public static string In100gOfProductProbablyShouldBeCaloriesButIs {
            get {
                return ResourceManager.GetString("In100gOfProductProbablyShouldBeCaloriesButIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient No {0} contains following errors. {1}
        ///.
        /// </summary>
        public static string IngredientNoContainsFollowingErrors {
            get {
                return ResourceManager.GetString("IngredientNoContainsFollowingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGREDIENT QUANTITY.
        /// </summary>
        public static string IngredientQuantity {
            get {
                return ResourceManager.GetString("IngredientQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingredients.
        /// </summary>
        public static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In serving of product, probably should be {0} calories (+/-{1} calories) but is {2} calories..
        /// </summary>
        public static string InServingOfProductProbablyShouldBeCaloriesButIs {
            get {
                return ResourceManager.GetString("InServingOfProductProbablyShouldBeCaloriesButIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to report the following bug:
        ///
        ///{0}.
        /// </summary>
        public static string IWouldLikeToReportTheFollowingBug {
            get {
                return ResourceManager.GetString("IWouldLikeToReportTheFollowingBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about CU and FPU....
        /// </summary>
        public static string LearnMoreAboutCuAndFpu {
            get {
                return ResourceManager.GetString("LearnMoreAboutCuAndFpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to license.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization of product database.
        /// </summary>
        public static string LocalizationOfProductDatabase {
            get {
                return ResourceManager.GetString("LocalizationOfProductDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEAL.
        /// </summary>
        public static string Meal {
            get {
                return ResourceManager.GetString("Meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meals.
        /// </summary>
        public static string Meals {
            get {
                return ResourceManager.GetString("Meals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string NameUppercase {
            get {
                return ResourceManager.GetString("NameUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information about nutritional value per unit {0}. Choose another unit..
        /// </summary>
        public static string NoInformationAboutNutritionalValuePerUnit {
            get {
                return ResourceManager.GetString("NoInformationAboutNutritionalValuePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name.
        /// </summary>
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No product.
        /// </summary>
        public static string NoProduct {
            get {
                return ResourceManager.GetString("NoProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified nutritional value per 100 g..
        /// </summary>
        public static string NotSpecifiedNutritionalValuePer100g {
            get {
                return ResourceManager.GetString("NotSpecifiedNutritionalValuePer100g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritional value per 100 g.
        /// </summary>
        public static string NutritionalValuePer100g {
            get {
                return ResourceManager.GetString("NutritionalValuePer100g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritional value per serving.
        /// </summary>
        public static string NutritionalValuePerServing {
            get {
                return ResourceManager.GetString("NutritionalValuePerServing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritional value per serving size is specified but description of serving size is not specified..
        /// </summary>
        public static string NutritionalValuePerServingSizeIsSpecifiedButDesc {
            get {
                return ResourceManager.GetString("NutritionalValuePerServingSizeIsSpecifiedButDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to older.
        /// </summary>
        public static string Older {
            get {
                return ResourceManager.GetString("Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} prot.
        /// </summary>
        public static string Prot {
            get {
                return ResourceManager.GetString("Prot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein (g).
        /// </summary>
        public static string ProteinG {
            get {
                return ResourceManager.GetString("ProteinG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protein (grams).
        /// </summary>
        public static string ProteinGrams {
            get {
                return ResourceManager.GetString("ProteinGrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of the ingredient was not specified..
        /// </summary>
        public static string QuantityOfTheIngredientWasNotSpecified {
            get {
                return ResourceManager.GetString("QuantityOfTheIngredientWasNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review this app.
        /// </summary>
        public static string ReviewThisApp {
            get {
                return ResourceManager.GetString("ReviewThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchUppercase {
            get {
                return ResourceManager.GetString("SearchUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select nutritional values to calculate (max. 4).
        /// </summary>
        public static string SelectNutritionalValuesToCalculateMax4 {
            get {
                return ResourceManager.GetString("SelectNutritionalValuesToCalculateMax4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to an e-mail address.
        /// </summary>
        public static string SendToAnEMailAddress {
            get {
                return ResourceManager.GetString("SendToAnEMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serving.
        /// </summary>
        public static string Serving {
            get {
                return ResourceManager.GetString("Serving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving description.
        /// </summary>
        public static string ServingDescription {
            get {
                return ResourceManager.GetString("ServingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving size.
        /// </summary>
        public static string ServingSize {
            get {
                return ResourceManager.GetString("ServingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving size in a different unit than grams is specified but its nutritional value is not specified..
        /// </summary>
        public static string ServingSizeInADifferentUnitThanGramsIsSpecifiedBut {
            get {
                return ResourceManager.GetString("ServingSizeInADifferentUnitThanGramsIsSpecifiedBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsUppercase {
            get {
                return ResourceManager.GetString("SettingsUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified description of serving size but not the size itself..
        /// </summary>
        public static string SpecifiedDescriptionOfServingSizeButNotTheSize {
            get {
                return ResourceManager.GetString("SpecifiedDescriptionOfServingSizeButNotTheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified serving size but not description of serving size..
        /// </summary>
        public static string SpecifiedServingSizeButNotDescriptionOfServingSize {
            get {
                return ResourceManager.GetString("SpecifiedServingSizeButNotDescriptionOfServingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions: dietphone@pabloware.com.
        /// </summary>
        public static string SuggestionsMail {
            get {
                return ResourceManager.GetString("SuggestionsMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product does not exist..
        /// </summary>
        public static string TheProductDoesNotExist {
            get {
                return ResourceManager.GetString("TheProductDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of calories in a serving size of the product is not proportional to the quantity in 100 g of product..
        /// </summary>
        public static string TheQuantityOfCaloriesInAServingSizeOfTheProductIs {
            get {
                return ResourceManager.GetString("TheQuantityOfCaloriesInAServingSizeOfTheProductIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of dietary fiber in a serving size of the product is not proportional to the quantity in 100 g of product..
        /// </summary>
        public static string TheQuantityOfDietaryFiberInAServingSizeOfThe {
            get {
                return ResourceManager.GetString("TheQuantityOfDietaryFiberInAServingSizeOfThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of fat in a serving size of the product is not proportional to the quantity in 100 g of product..
        /// </summary>
        public static string TheQuantityOfFatInAServingSizeOfTheProductIsNot {
            get {
                return ResourceManager.GetString("TheQuantityOfFatInAServingSizeOfTheProductIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of protein in a serving size of the product is not proportional to the quantity in 100 g of product..
        /// </summary>
        public static string TheQuantityOfProteinInAServingSizeOfTheProductIs {
            get {
                return ResourceManager.GetString("TheQuantityOfProteinInAServingSizeOfTheProductIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of total carbohydrates in a serving size of the product is not proportional to the quantity in 100 g of product..
        /// </summary>
        public static string TheQuantityOfTotalCarbohydratesInAServingSizeOfThe {
            get {
                return ResourceManager.GetString("TheQuantityOfTotalCarbohydratesInAServingSizeOfThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There may not be more dietary fiber than carbohydrates total..
        /// </summary>
        public static string ThereMayNotBeMoreDietaryFiberThanCarbohydrates {
            get {
                return ResourceManager.GetString("ThereMayNotBeMoreDietaryFiberThanCarbohydrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category includes other products. Change their category and try again..
        /// </summary>
        public static string ThisCategoryIncludesOtherProducts {
            get {
                return ResourceManager.GetString("ThisCategoryIncludesOtherProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We invite you to visit this page for information about latest version of the app:.
        /// </summary>
        public static string WeInviteYouToVisitThisPageForInformationAbout {
            get {
                return ResourceManager.GetString("WeInviteYouToVisitThisPageForInformationAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what&apos;s new.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change localization of product database many times. This is useful if you travel often..
        /// </summary>
        public static string YouCanChangeLocalizationOfProductDatabaseManyTimes {
            get {
                return ResourceManager.GetString("YouCanChangeLocalizationOfProductDatabaseManyTimes", resourceCulture);
            }
        }
    }
}
